import pandas as pd

materias = [
    'AEA4 - Aplicaciones de Electrónica Analógica',
    'AEA5 - Aplicaciones de Electrónica Analógica',
    'AEA6 - Aplicaciones de Electrónica Analógica',
    'AED4 - Aplicaciones de Electrónica Digital',
    'AED5 - Aplicaciones de Electrónica Digital',
    'AED6 - Aplicaciones de Electrónica Digital',
    'AUT4 - Automación',
    'DASE - Diseño Asistido y Simulación Electrónica',
    'DITEC4 - Dibujo Tecnológico',
    'DPM4-2E - CNC 2 Ejes',
    'DPM4-3E - CNC 3 Ejes',
    'DPM4-FM - Taller – Fresadora Básica',
    'DPM4-TM - Taller – Tornería Básica',
    'DPM6-3D - Diseño y procesamiento mecánico impresión 3D',
    'DPM6-3E - Diseño y procesamiento mecánico CNC 3E',
    'DPM6-CC - Diseño y procesamiento mecánico Cadena Cinemática',
    'EA7 - Electrónica Aplicada',
    'EI7 - Electrónica Industrial',
    'EM7 - ELEMENTOS DE MAQUINA',
    'EPYDL6 - Emprendimiento Productivo y Desarrollo Local',
    'ET6 - Electrotecnia',
    'IAE4 - Instalaciones y Aplicaciones de la Energía',
    'IAE5 - Instalaciones y Aplicaciones de la Energía',
    'IAE6-GD - Instalaciones y aplicación de la energía IAE Generación, Transmisión y Distribución de la Energía Eléctrica',
    'IAE6-LT - Instalaciones y Aplicaciones de la Energía: Luminotecnia',
    'IAE6-MO - Motores de Combustión Interna',
    'II7 - Instalaciones Industriales',
    'IME6 - Instalaciones y Máquinas Eléctricas',
    'LE5 - Lenguajes Electrónicos',
    'LE6 - Lenguajes Electrónicos',
    'LME6 - Laboratorio Mediciones Eléctricas',
    'LMyCC7 - LABORATORIO DE METROLOGIA Y CONTROL DE CALIDAD',
    'LT1 - Lenguajes Tecnológicos',
    'MEyA4 - MAQUINAS ELECTRICAS Y AUTOMATISMOS',
    'MEyA6 - Maquinas Eléctricas y Automatismos',
    'MPE4 - Montaje de Proyectos Electrónicos',
    'MPE5 - Montaje de Proyectos Electrónicos',
    'MPE6 - Montaje de Proyectos Electrónicos',
    'MyM5 - Mecánica y Mecanismos',
    'MyME7 - MANTENIMIENTO Y MONTAJE ELECTROMECANICO',
    'PyDE7 - Proyecto y Diseño Electrónico',
    'PyDEM7 - PROYECTO Y DISEÑO ELECTROMECANICO',
    'PyDIE7 - Proyecto y Diseño de Instalaciones eléctricas.',
    'RyEM5 - Resistencia y Ensayo de Materiales',
    'SCOM6 - Sistemas de Comunicaciones',
    'SCOM7 - Sistemas de Comunicaciones',
    'SCTRL7 - Sistemas de Control',
    'SHyPA5 - SHyPA',
    'SHyPA7 - (no usar)',
    'SM6 - Sistemas Mecánicos',
    'SM7 - Sistemas Mecánicos',
    'SP6 - Sistemas Productivos',
    'ST1 - Sistemas Tecnológicos',
    'TE4 - Tecnología Electrónica (no usar)',
    'TyMT6 - TERMODINÁMICA Y MÁQUINAS TÉRMICAS',
    'DPM5-2E - CNC 2 Ejes',
    'DPM5-3E - CNC 3 Ejes',
    'DPM5-FM - Taller – Fresadora Básica',
    'DPM5-TM - Taller – Tornería Básica',
    'AEM5-Aplicaciones Electromecánica',
    'CE4- Circuitos Eléctricos',
    'CE5- Circuitos Eléctricos',
    'EA4 - Aplicaciones de Electrónica Analógica',
    'LT2- Lenguajes Tecnológicos',
    'LT3 -Lenguajes Tecnológicos',
    'ME7- Maquinas Eléctricas',
    'MEyA5- ME- Maquinas Eléctricas',
    'MEyA5- RI- Robotica Industrial',
    'RI6 - Robótica Industrial',
    'RI7- Robótica Industrial',
    'ST2- Sistemas Tecnológicos',
    'ST3 - Sistemas Tecnológicos',
    'TM4- Tecnología de los Materiales',
    'TME5- Taller de Mediciones Electrónicas',
    'TME6 - Taller de Mediciones Electrónicas',
    'PT1-AE - Ajustes y Estructuras',
    'PT1-EL - Electrónica',
    'PT1-EL - Electrónica',
    'PT1-ET - Electricidad',
    'PT1-MH - Maquinas y herramientas - Impresión 3D',
    'PT1-MT - Materiales',
    'PT2-AE - Ajustes y Estructuras',
    'PT2-EL - Electrónica',
    'PT2-ET - Electricidad',
    'PT2-MH - Maquinas y herramientas',
    'PT2-MT - Materiales',
    'PT3-AE - Ajustes y Estructuras',
    'PT3-EL - Electrónica',
    'PT3-ME - Metrologia',
    'PT3-MH - Maquinas y herramientas',
    'PT3-MT - Materiales',
    'AUT3- Automación',
    'MNTE7 - Mantenimiento electrónico',
    'IA7 - Inteligencia Artificial',
    'GR7- Grippers Robóticos',
    'EMG- Electromecánica Gral',
    'PRG1 - Programación 1',
    'ELG- Electrónica Gral'
]

df = pd.DataFrame({'Nombre de la Materia': materias})
df.to_excel('Materias_Formulario.xlsx', index=False)
print(f"Successfully wrote {len(df)} rows to Materias_Formulario.xlsx")
